name: Deploy Frontend and API

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  # Deploy API to Azure Functions
  deploy_api:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Deploy API Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Configure NuGet Sources
        run: |
          # Add GitHub Package Registry sources for private packages
          # Using NUGET_AUTH_TOKEN which should be set to a GitHub PAT with package:read permissions
          dotnet nuget add source "https://nuget.pkg.github.com/elielijah321/index.json" \
            --name "GithubPackages" \
            --username "elielijah321" \
            --password "${{ secrets.NUGET_AUTH_TOKEN }}" \
            --store-password-in-clear-text
          
          dotnet nuget add source "https://nuget.pkg.github.com/DFE-Digital/index.json" \
            --name "DfE" \
            --username "elielijah321" \
            --password "${{ secrets.NUGET_AUTH_TOKEN }}" \
            --store-password-in-clear-text
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build and Deploy API
        run: |
          cd API
          echo "🚀 Starting Azure Function deployment..."
          
          # Clean previous builds
          rm -rf ./publish-direct
          rm -f ./deploy.zip
          
          # Restore dependencies
          echo "📦 Restoring .NET dependencies..."
          dotnet restore API.csproj
          
          # Publish .NET 8 isolated function with explicit settings
          echo "🔨 Publishing .NET 8 Azure Functions..."
          dotnet publish API.csproj \
            --configuration Release \
            --output ./publish-direct \
            --runtime win-x64 \
            --self-contained false \
            --verbosity normal
          
          # Verify the output
          echo "📁 Published files:"
          ls -la ./publish-direct/
          
          # Check if API.exe exists
          if [ -f "./publish-direct/API.exe" ]; then
            echo "✅ API.exe found in publish directory"
          else
            echo "❌ API.exe not found! Available files:"
            find ./publish-direct/ -name "*.exe" -o -name "*.dll" | head -10
          fi
          
          # Create zip package
          echo "📦 Creating deployment package..."
          cd ./publish-direct
          zip -r ../deploy.zip .
          cd ..
          
          # Deploy to Azure Function App
          echo "🚀 Deploying to Azure Function App..."
          az functionapp deployment source config-zip \
            --name "c-kitchen" \
            --resource-group "c-kitchen-rg" \
            --src ./deploy.zip
          
          # Restart function app
          echo "🔄 Restarting function app..."
          az functionapp restart \
            --name "c-kitchen" \
            --resource-group "c-kitchen-rg"
          
          # Wait for restart
          echo "⏳ Waiting for function app to restart..."
          sleep 30
          
          # Test the deployment
          echo "🧪 Testing the deployed function..."
          FUNCTION_URL="https://c-kitchen.azurewebsites.net/api/test"
          curl -f "$FUNCTION_URL" || echo "❌ Function test failed (may be normal if no test endpoint exists)"
          
          # Cleanup
          rm -rf ./publish-direct
          rm -f ./deploy.zip
          
          echo "✅ API deployment completed successfully!"

  # Deploy Frontend to Azure Static Web Apps
  build_and_deploy_frontend:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy Frontend
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_POND_07F0A8010 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "/" # App source code path
          api_location: "" # Api source code path - keep empty since API is deployed separately
          output_location: "dist" # Built app content directory
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_POND_07F0A8010 }}
          action: "close"

